wg_path: <%= ENV['WG_PATH'] || 'etc' %>
wg_device: <%= ENV['WG_DEVICE'] || 'eth0' %>
wg_default_address: <%= ENV['WG_DEFAULT_ADDRESS'] || '10.8.0.x' %>
wg_default_address_6: <%= ENV['WG_DEFAULT_ADDRESS_6'] || 'fdcc:ad94:bacf:61a4::cafe:x' %>
wg_allowed_ips: <%= ENV['WG_ALLOWED_IPS'] || '0.0.0.0/0, ::/0' %>
wg_host: <%= ENV['WG_HOST'] || '0.0.0.0' %>
wg_port: <%= ENV['WG_PORT'] || '51820' %>
wg_default_dns: <%= ENV['WG_DEFAULT_DNS'] || '1.1.1.1' %>
wg_default_dns_6: <%= ENV['WG_DEFAULT_DNS_6'] || '2606:4700:4700::1111' %>
wg_pre_up: <%= ENV['WG_PRE_UP'] || '' %>
wg_pre_down: <%= ENV['WG_PRE_DOWN'] || '' %>
wg_post_up: <%= ENV['WG_POST_UP'] %>
wg_post_down: <%= ENV['WG_POST_DOWN'] %>
wg_persistent_keepalive: <%= ENV['WG_PERSISTENT_KEEPALIVE'] || 0 %>
auth_token: <%= ENV['AUTH_TOKEN'] %>
auth_digest_token: <%= ENV['AUTH_DIGEST_TOKEN'] %>
webhooks_url: <%= ENV['WEBHOOKS_URL'] %>
connecting_client_limit: <%= ENV['CONNECTING_CLIENT_LIMIT'] || '24' %>
