wg_path: <%= ENV['WG_PATH'] || 'etc' %>
wg_device: <%= ENV['WG_DEVICE'] || 'eth0' %>
wg_default_address: <%= ENV['WG_DEFAULT_ADDRESS'] || '10.8.0.x' %>
wg_allowed_ips: <%= ENV['WG_ALLOWED_IPS'] || '0.0.0.0/0, ::/0' %>
wg_host: <%= ENV['WG_HOST'] || '0.0.0.0' %>
wg_port: <%= ENV['WG_PORT'] || '51820' %>
wg_default_dns: <%= ENV['WG_DEFAULT_DNS'] || '1.1.1.1' %>
wg_pre_up: <%= ENV['WG_PRE_UP'] || '' %>
wg_pre_down: <%= ENV['WG_PRE_DOWN'] || '' %>
wg_post_up: <%= ENV['WG_POST_UP'] %>
wg_post_down: <%= ENV['WG_POST_DOWN'] %>
wg_persistent_keepalive: <%= ENV['WG_PERSISTENT_KEEPALIVE'] || 0 %>
auth_token: <%= ENV['AUTH_TOKEN'] %>
